#!/bin/bash

# Unix evaluation v1 - Faustine Massin

# Script to install MediaWiki on CentOS 7
# MediaWiki is a free and open-source wiki application written in PHP
# it allows to create a wiki sites
# MediaWiki's homepage : https://www.mediawiki.org.

# Check for latest release of mediawiki on : https://www.mediawiki.org/wiki/Download
ARCHIVE_URL="https://releases.wikimedia.org/mediawiki/1.28/mediawiki-1.28.0.tar.gz"
HTDOCS_PATH=/var/www/html
WWW_SUBFOLDER="mediawiki"

pause() {
        echo "Press <Enter> to continue..."
        read touche
        case $touche in
        *)      echo ""
                ;;
        esac
}

echo ""
echo " ----------- INSTALLATION OF MediaWiki ON CentOS 7 ----------- "
echo ""

#### Check if the user have root privileges ####
if [[ $EUID -ne 0 ]]; then
  echo ""
  echo "You must be a root user in order to run this script !"
  echo "Connect as root then try again."
  echo ""
  exit 1
fi

##### Before installing any package, packages and repository should be up to date. ####
echo ""
echo "----------- Update packages and repository ----------- "
yum -y update
echo ""
echo "Packages and repository are now up to date."
echo "System ready for new packages installation."
echo ""

#### PHP INSTALLATION ####
echo ""
echo "----------- PHP INSTALLATION AND SETTINGS----------- "
echo ""

# TO DO : manage error message "Failed to set locale, defaulting to C"

# Since MediaWiki version 1.27, it uses a PHP version greater than 5.5.
# The YUM repository contains PHP version 5.4 only.
# Use the Webtatic repository to install a version of PHP greater than 5.5.

# Installing EPEL repository (required to install Webtatic repository)
yum -y install epel-release
yum -y update
clean all
# Installing Webtatic repository
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
yum -y update
yum clean all

# PHP modules and extensions installation
yum -y install php55w php55w-mysql php55w-xml php55w-intl php55w-gd php55w-mbstring texlive

echo ""
echo "--> PHP version :"
php -v

# Manage PHP settings
PHP_TIME_OK=$(grep -v ";" /etc/php.ini | grep date.timezone | wc -l)
if [[ $PHP_TIME_OK -eq 0 ]] ; then
        sed -i.bck 's/;date.timezone =/date.timezone = UTC/g' /etc/php.ini
fi

echo ""
echo " ----------- Apache HTTPD server INSTALLATION ----------- "
echo ""
#### Apache HTTPD server  INSTALLATION ####
yum install -y httpd
systemctl start httpd              # Start Apache web server
systemctl enable httpd             # Enable Apache Server to start at boot time

echo ""
echo "The Apache server is now running."
echo "You can connect to the server by entering your IP address in a web broswer."
echo ""
pause

echo ""
echo " ----------- MariaDB INSTALLATION ----------- "
echo ""
#### MariaDB INSTALLATION ####
# MariaDB is a fork of MySQL

yum install -y mariadb-server #mariadb   # to do : est ce necessaire ?
systemctl start mariadb             # Start MariaDB
systemctl enable mariadb            # Enable MariaDB to start at boot time

# Secure MariaDB installation
# TO DO : a revoir
yum -y install expect
MYSQL_ROOT_PASSWORD=abcd1234
SECURE_MYSQL=$(expect -c "
set timeout 10
spawn mysql_secure_installation
expect \"Enter current password for root (enter for none):\"
send \"$MYSQL\r\"
expect \"Change the root password?\"
send \"n\r\"
expect \"Remove anonymous users?\"
send \"y\r\"
expect \"Disallow root login remotely?\"
send \"y\r\"
expect \"Remove test database and access to it?\"
send \"y\r\"
expect \"Reload privilege tables now?\"
send \"y\r\"
expect eof
")
echo "$SECURE_MYSQL"
yum remove expect -y

#### DATABASE CREATION ####
echo ""
echo " ----------- DATABASE CREATION AND CONFIGURATION ----------- "
echo ""
### Configure database
DB_USER=wikiUser
DB_PASS=Passw0rd123$
DB_NAME=wikimediaDb
BASE_URL="/$WWW_SUBFOLDER/"
ANSWER=""

# The user can either use default value for login, password and database name or enter new one.
echo ""
echo "By default database connexion id is : $DB_USER and password is : $DB_PASS."
while true; do
    read -p "Do you want to keep this values ? (y/n)" yn
    case "$yn" in   #To do : faut il enlever les quotes
        [Yy] ) echo "You will use default values"; break;;
        [Nn] ) read -r -p "Enter new id : " DB_USER ; read -r -p "Enter new password : " DB_PASS ; break;;
        # To do : ne pas voir le mdp que le user entre
        * ) echo "Please answer y or n.";;
    esac
done

echo ""
echo "By default database name is : $DB_NAME."
while true; do
    read -p "Do you want to keep this value ? (y/n)" yn
    case "$yn" in   #To do : faut il enlever les quotes
        [Yy] ) echo "You will use default values"; break;;
        [Nn] ) read -r -p "Enter new database name : " DB_NAME ; break;;
        # To do : ne pas voir le mdp que le user entre
        * ) echo "Please answer y or n.";;
    esac
done

echo ""

# Ensure that the database wikimediaDb does not already exist.
# TO DO : a revoir
RESULT="mysqlshow --user=$DB_USER --password=$DB_PASS $DB_NAME| grep -v Wildcard | grep -o $DB_NAME"

# Check if the database as already been created.# to do : a revoir
if [ "$RESULT" == "$DB_NAME" ]; then
    echo "Database $DB_NAME already exist."
  else
    echo "Database $DB_NAME not exist."
fi

# 1. Login to MySQL command line
# 2. Create a database
# 3. Create a new database user (using root user is not recommended for the databases)
# 4. Amend privileges.

echo " Please enter the user root password of the database (default : root)."
mysql -u root -p << EOF
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
grant ALL PRIVILEGES on $DB_NAME.* to '$DB_USER'@'localhost' ;
FLUSH PRIVILEGES;
EOF

#### MediaWiki INSTALLATION ####
echo " ----------- MediaWiki INSTALLATION ----------- "
# Download MediaWiki Server from archive
curl -OL -k "$ARCHIVE_URL"

# If the system encounter a problem while downloading the archive :
if [[ $? -ne 0 ]]; then
  # Check internet connexion
  echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo ""
    echo " You are offline !"
    echo " Check your internet connexion then retry."
  else
    echo ""
    echo " Archive error."
    echo " Please check the archive url before trying again."
  fi
  exit 1
fi

# Unpack the package
tar xvf mediawiki-1.28.0.tar.gz
# If the system encounter a problem while unpacking the archive :
if [[ $? -ne 0 ]]; then
  # Check internet connexion
  echo ""
  echo "Archive error."
  echo " Please check the archive url before trying again."
  exit 1
fi

# Move the MediaWiki files to the webroot directory of Apache web server.
mv mediawiki-1.28.0/* "$HTDOCS_PATH"
# To do : remplacer par variable 1-28....

# Set appropriate permissions to the Apache process over Apache web root directory
chown -R apache:apache /var/www/html
chmod -R 755 /var/www/html
# to do : ajout de variables

# Restart the Apache service
systemctl restart httpd

echo ""
echo " ----------- Accessing MediaWiki ----------- "
echo ""
echo "Open a browser and navigate to the web installer using http://server-ip and complete the required steps to finish the installation."
echo ""

while true; do
    read -p "Do you encounter a message saying \"Forbidden You don't have permission to access on this server.\" ? (y/n)" yn
    case "$yn" in
      # If yes, disable the SELinux and restart the Apache server
        [Yy] ) setenforce 0 ; systemctl restart httpd ; echo "SELinux disabled. Refresh your broswer tab."; break;;
        [Nn] ) break;;
        * ) echo "Please answer y or n.";;
    esac
done

# to do : ajouter des pauses

echo ""
echo " ----------- Web installation and personnalisation ----------- "
echo ""
echo " 1. Language"
echo "Select the language to use in the installation and the Wiki language from drop down menu."
echo "Click on \" Continue \" button to proceed to the next step."
echo ""
echo " 2. Welcome to MediaWiki!"
echo "Click on \" Continue \" button to proceed to the next step."
echo ""
echo " 3. Connect to database"
echo "Select MySQL as the database type."
echo "Leave localhost in the value of database host."
echo "Provide the name of your database : DB_USER"
echo "Provide the username and password of the database user which you have created."
echo "Click Continue to proceed further."
echo ""
echo " 4. Database settings"
echo "Database used for web access : leave the option checked."
echo "Storage engine and character set to use : leave the default option check for both of these options."
echo ""
echo " 5. Name"
echo "Enter the name of your Wiki."
echo "Enter project namespace (you can use the default name of your Wiki)."
echo "Create the administrator account by providing the username, password and administrator email address."
echo ""
echo " 6. Install"
echo "You can now onfigure more options by cliking \"Ask me more questions.\"."
echo "To install the wiki clik on \"I\'m bored already, just install the wiki.\"."
echo "Click Continue to proceed the installation."
echo ""
echo "MediaWiki is installed."
echo ""
echo "The installer has generated a LocalSettings.php file, which contains the configuration of the MediaWiki."
echo " Click on \"Download LocalSettings.php\", if it did not start automatically."
echo ""
echo " The LocalSettings.php file must be in ...... directory"
# Place LocalSettings.php file in the base of the wiki installation.
# vi /var/www/html/LocalSettings.php
echo ""
echo " You can now enter your wiki !"

exit 0
